services:
  - type: web
    name: mandisense-api
    runtime: docker
    plan: free
    region: ohio
    branch: main
    autoDeploy: true
    envVars:
      - key: APP__ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mandisense-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: mandisense-redis
          type: redis
          property: connectionString


databases:
  - name: mandisense-db
    plan: free
    postgresMajorVersion: 15

redis:
  - name: mandisense-redis
    plan: free
    ipAllowList: [] # Only allow internal access
